export const GITHUB = "https://www.github.com"
export const LINKEDIN = "https://www.linkedin.com"
export const FACEBOOK = "https://www.facebook.com"
export const INSTAGRAM = "https://www.instagram.com"
export const TWITTER = "https://www.twitter.com"