export const GITHUB = "https://github.com/adityasmeshram/"
export const LINKEDIN = "https://www.linkedin.com/in/adityasmeshram/"
export const FACEBOOK = "https://www.facebook.com/aditya.meshram.3958/"
export const INSTAGRAM = "https://www.instagram.com/adityasm98/"
export const TWITTER = "https://twitter.com/adityasmeshram"